# Generated by Django 4.0.2 on 2022-04-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstjob', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentuser',
            old_name='images',
            new_name='image',
        ),
    ]
