# Generated by Django 4.0.2 on 2022-04-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstjob', '0002_rename_images_studentuser_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiter',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
